#!/bin/sh

# sourced at boot by ~/.xinitrc and most display managers

# set display timeout, sleep, and power off times
xset dpms 600 900 1200

#set touchpad properties
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" 0.6
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Middle Emulation Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1

# set keyboard repeat rate
xset r rate 160 80

# set gamma value
xgamma -gamma 1

# left hand mouse
#xmodmap -e "pointer = 3 2 1"

# set background
~/.fehbg

# starting picom
picom & disown

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
pgrep xss-lock && killall xss-lock

xss-lock --transfer-sleep-lock -- i3lock \
	--color=00000022 --time-color=ffffffbb --date-color=ffffffbb \
	--wrong-text="" --greeter-text="Locked" --noinput-text="󰌐" \
	--{time,date,greeter,verif,layout}-font="Ubuntu" \
	--wrong-font="Symbols Nerd Font" --wrong-size=50 --wrong-pos="w/2:h/2+15"  \
	--time-size=43 --greeter-size=35 \
	--verif-text="..." --verif-pos="w/2:h/2+3" --verif-size=47 \
	--{time,date,greeter,wrong,verif,layout}-color=ffffffbb --wrong-color=ffffffbb \
	--time-str="%H:%M" \
	--pass-{media,screen,power,volume}-keys \
	\
	-k --indicator --radius=110 --ring-width=6 \
	\
	--inside-color=00000000 --insidever-color=00000000 --insidewrong-color=55000033 \
	--ring-color=ffffff77 --ringver-color=ffffff77 --ringwrong-color=ffddddaa \
	--line-uses-inside --separator-color=00000000 \
	\
	--keyhl-color=ffffffff --bshl-color=00000033 \
	-e & disown

sct 3000
