#!/bin/sh

# sourced at boot by ~/.xinitrc and most display managers

# set display timeout, sleep, and power off times
xset dpms 600 900 1200

#set touchpad properties
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" 0.6
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Middle Emulation Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1

# set keyboard repeat rate
xset r rate 160 80

# set gamma value
xgamma -gamma 1

# left hand mouse
#xmodmap -e "pointer = 3 2 1"

# set background
feh --no-fehbg --bg-fill ~/.wallpaper

# starting picom
picom --animations --experimental-backends -b & disown

# xss-lock grabs a logind suspend inhibit lock and will use i3lock to lock the
# screen before suspend. Use loginctl lock-session to lock your screen.
pgrep xss-lock | killall xss-lock
xss-lock --transfer-sleep-lock -- i3lock --color=00000033 --time-color=ffffffbb --date-color=ffffffbb --indicator -k --radius=110 --ring-width=6 --inside-color=00000000 --insidever-color=00000000 --line-uses-inside --ring-color=ffffff77 --separator-color=00000000 --keyhl-color=ffffffff --bshl-color=00000033 --wrong-text="Wrong" --greeter-text="Locked" --greeter-color=ffffffbb --{time,date,greeter,wrong,verif,layout}-color=ffffffbb --wrong-color=ffffffbb --{time,date,greeter,wrong,verif,layout}-font="Ubuntu" --ringver-color=ffffff77 --insidever-color=00000000 --ringwrong-color=ffddddaa --insidewrong-color=55000033  -e & disown

sct 3000
